<#
DISCLAIMER:
These sample scripts are not supported under any Lenovo standard support
program or service. The sample scripts are provided AS IS without warranty
of any kind. Lenovo further disclaims all implied warranties including,
without limitation, any implied warranties of merchantability or of fitness for
a particular purpose. The entire risk arising out of the use or performance of
the sample scripts and documentation remains with you. In no event shall
Lenovo, its authors, or anyone else involved in the creation, production, or
delivery of the scripts be liable for any damages whatsoever (including,
without limitation, damages for loss of business profits, business interruption,
loss of business information, or other pecuniary loss) arising out of the use
of or inability to use the sample scripts or documentation, even if Lenovo
has been advised of the possibility of such damages.
#>
#
# Module manifest for module 'Lenovo.Client.Scripting'
#
# Generated by: Lenovo Commercial Deployment Readiness Team
#
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Lenovo.Client.Scripting.psm1'

# Version number of this module.
ModuleVersion = '2.4.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '724570ce-b9fa-4c3e-99d4-0131dbb25d2c'

# Author of this module
Author = 'Lenovo Commercial Deployment Readiness Team'

# Company or vendor of this module
CompanyName = 'Lenovo'

# Copyright statement for this module
Copyright = '(c) Copyright 2026 Lenovo Ltd.'

# Description of the functionality provided by this module
Description = 'Collection of cmdlets to simplify the management and support of Lenovo Commercial PCs.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    "Add-LnvMTOS",
    "Add-LnvSUCommandLine",
    "Add-LnvSULogging",
    "Export-LnvUpdateRetrieverConfig",
    "Find-LnvBiosCode",
    "Find-LnvBiosInfo",
    "Find-LnvDockModel",
    "Find-LnvDriverPack",
    "Find-LnvHSAPack",
    "Find-LnvMachineType",
    "Find-LnvModel",
    "Find-LnvTool",
    "Find-LnvUpdate",
    "Get-LnvAvailableBiosVersion",
    "Get-LnvBatteryInfo",
    "Get-LnvBiosCode",
    "Get-LnvBiosInfo",
    "Get-LnvBiosPasswordsSet",
    "Get-LnvBiosUpdateUrl",
    "Get-LnvBiosVersion",
    "Get-LnvCVE",
    "Get-LnvDriverPack",
    "Get-LnvMachineType",
    "Get-LnvModelName",
    "Get-LnvMTOSList",
    "Get-LnvProductNumber",
    "Get-LnvSerial",
    "Get-LnvSystemFirmwareVersion",
    "Get-LnvUpdatesNotification",
    "Get-LnvWarranty",
    "Get-LnvWUFriendlyName",
    "Invoke-LnvCVLogViewer",
    "Invoke-LnvTILogViewer",
    "Remove-LnvMTOS",
    "Show-LnvApplicableUpdate",
    "Show-LnvUpdatesHistory"
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

PSData = @{

# Tags applied to this module. These help with module discovery in online galleries.
# Tags = @()

# A URL to the license for this module.
# LicenseUri = ''

# A URL to the main website for this project.
# ProjectUri = ''

# A URL to an icon representing this module.
# IconUri = ''

# ReleaseNotes of this module
# ReleaseNotes = ''

} # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

# SIG # Begin signature block
