# https://remark.js.org

plugins:
- remark-preset-lint-markdown-style-guide
- [remark-lint-definition-case, false]
- [remark-lint-fenced-code-flag, false]
- [remark-lint-maximum-line-length, 120]
- [remark-lint-no-duplicate-headings, false]
- [remark-lint-no-file-name-irregular-characters, false]
