<#
.SYNOPSIS
    TI Log File Viewer - Parses Lenovo ThinInstaller log files and produces a concise summary.

.DESCRIPTION
    Analyzes log files generated by Lenovo ThinInstaller and provides a human-readable
    summary of key session details including system information, applicable updates,
    installation results, and errors.

.PARAMETER LogFile
    Path to a single ThinInstaller log file.

.PARAMETER LogDirectory
    Path to a directory containing ThinInstaller log files (.txt and .log).

.PARAMETER OutputFile
    Optional path to write the summary to a plain text file.

.PARAMETER Force
    Overwrite the output file without prompting.

.PARAMETER NoColor
    Suppress color output (useful for redirected output).

.EXAMPLE
    .\TI-LogFileViewer.ps1 -LogFile "C:\Logs\Update_log_250221164004.txt"

.EXAMPLE
    .\TI-LogFileViewer.ps1 -LogDirectory "C:\Logs" -OutputFile "C:\Logs\summary.txt"

.NOTES
    Version: 1.0
    Requires: PowerShell 5.1 or later
#>
function Invoke-LnvTILogViewer {
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$LogFile,

    [Parameter(Mandatory = $false)]
    [string]$LogDirectory,

    [Parameter(Mandatory = $false)]
    [string]$OutputFile,

    [switch]$Force,

    [switch]$NoColor
)

$ScriptVersion = "1.0"
$ScriptName = "TI Log File Viewer"

#region Helper Functions

function Write-ColorHost {
    param(
        [string]$Text,
        [ConsoleColor]$ForegroundColor = [ConsoleColor]::White,
        [switch]$NoNewline
    )
    if ($script:NoColor) {
        if ($NoNewline) { Write-Host $Text -NoNewline }
        else { Write-Host $Text }
    }
    else {
        if ($NoNewline) { Write-Host $Text -ForegroundColor $ForegroundColor -NoNewline }
        else { Write-Host $Text -ForegroundColor $ForegroundColor }
    }
}

function Get-RebootTypeLabel {
    param([string]$RebootType)
    switch ($RebootType) {
        "0" { "No reboot" }
        "1" { "Forced reboot" }
        "3" { "Reboot recommended" }
        default { "Unknown ($RebootType)" }
    }
}

function Get-SearchScopeLabel {
    param([string]$Scope)
    switch ($Scope) {
        "A" { "All updates (-searchA)" }
        "C" { "Critical updates (-searchC)" }
        "R" { "Recommended updates (-searchR)" }
        default { $Scope }
    }
}

function ParseHeaderDateTime {
    <#
    .SYNOPSIS
        Parses the session datetime from line 1 of the TI log.
        Handles multiple locale formats:
          - English: 4/6/2023 2:18:38 PM
          - Spanish: 21/02/2025 4:40:04 p. m.
          - ISO-ish: 2025-08-01 11:43:46 AM
    #>
    param([string]$DateTimeStr)

    $DateTimeStr = $DateTimeStr.Trim()

    # Normalize non-breaking spaces (U+00A0) to regular spaces
    $normalized = $DateTimeStr -replace [char]0x00A0, ' '

    # Normalize Spanish AM/PM markers to standard
    $normalized = $normalized -replace '\s*a\.\s*m\.', ' AM'
    $normalized = $normalized -replace '\s*p\.\s*m\.', ' PM'

    # Try various formats
    $formats = @(
        "dd/MM/yyyy h:mm:ss tt",
        "dd/MM/yyyy hh:mm:ss tt",
        "dd/MM/yyyy H:mm:ss",
        "dd/MM/yyyy HH:mm:ss",
        "M/d/yyyy h:mm:ss tt",
        "M/d/yyyy hh:mm:ss tt",
        "M/d/yyyy H:mm:ss",
        "M/d/yyyy HH:mm:ss",
        "yyyy-MM-dd h:mm:ss tt",
        "yyyy-MM-dd hh:mm:ss tt",
        "yyyy-MM-dd H:mm:ss",
        "yyyy-MM-dd HH:mm:ss"
    )

    foreach ($fmt in $formats) {
        try {
            $parsed = [DateTime]::ParseExact($normalized, $fmt, [System.Globalization.CultureInfo]::InvariantCulture)
            return $parsed
        }
        catch {
            continue
        }
    }

    # Fallback: try generic parse
    try {
        return [DateTime]::Parse($normalized, [System.Globalization.CultureInfo]::InvariantCulture)
    }
    catch {
        return $null
    }
}

function Test-ThinInstallerLog {
    param([string]$FilePath)
    try {
        $firstLine = Get-Content -Path $FilePath -TotalCount 1 -ErrorAction Stop
        return $firstLine -match '^\[Thin Installer build:'
    }
    catch {
        return $false
    }
}

function ParseThinInstallerLog {
    param([string]$FilePath)

    $result = [PSCustomObject]@{
        FileName           = [System.IO.Path]::GetFileName($FilePath)
        FilePath           = $FilePath
        SessionDateTime    = $null
        SessionDateStr     = "(not found)"
        TIVersion          = "(not found)"
        TIBuildDate        = "(not found)"
        WindowsVersion     = "(not found)"
        MTM                = "(not found)"
        OS                 = "(not found)"
        OSLanguage         = "(not found)"
        ActiveLanguage     = "(not found)"
        DefaultLanguage    = "(not found)"
        SearchScope        = "(not found)"
        ActionType         = "(not found)"
        CommandString      = "(not found)"
        CandidateList      = @()
        ApplicableCount    = 0
        InstalledUpdates   = @()
        FailedUpdates      = @()
        FailureReasons     = @{}
        ProcessedAtShutdown = @()
        SevereEntries      = @()
        WarningEntries     = @()
        IsScanOnly         = $false
        RebootSummary      = "No reboot needed"
    }

    try {
        $lines = Get-Content -Path $FilePath -Encoding UTF8 -ErrorAction Stop
    }
    catch {
        Write-Error "Cannot read file: $FilePath - $_"
        return $null
    }

    $lineCount = $lines.Count

    # === Parse Header (Line 1) ===
    if ($lineCount -gt 0 -and $lines[0] -match '^\[Thin Installer build:\s*(\d{4}-\d{2}-\d{2})\s+Version:\s*([^\]]+)\]\t(.+)$') {
        $result.TIBuildDate = $Matches[1]
        $result.TIVersion = $Matches[2].Trim()
        $parsedDate = ParseHeaderDateTime $Matches[3]
        if ($parsedDate) {
            $result.SessionDateTime = $parsedDate
            $result.SessionDateStr = $parsedDate.ToString("yyyy-MM-dd HH:mm:ss")
        }
        else {
            $result.SessionDateStr = $Matches[3].Trim()
        }
    }

    # Track state for multi-line parsing
    $inCandidateList = $false
    $candidateListFound = $false
    $inSystemProps = $false
    $systemPropsLines = @()
    #$inLanguageBlock = $false
    #$lastFailedPackageId = ""
    #$lastExpectedReturnCode = ""
    #$lastActualReturnCode = ""
    $updateResponseSizes = @()

    for ($i = 1; $i -lt $lineCount; $i++) {
        $line = $lines[$i]

        # === Windows Version ===
        if ($line -match 'Message:\s*Microsoft Windows \[Vers[^\]]*\s+([\d\.]+)\]') {
            $result.WindowsVersion = "Microsoft Windows $($Matches[1])"
        }

        # === Language Block ===
        if ($line -match 'The active language is:\s*(.+)') {
            $result.ActiveLanguage = $Matches[1].Trim()
        }
        if ($line -match 'The default language is:\s*(.+)') {
            $result.DefaultLanguage = $Matches[1].Trim()
        }
        if ($line -match 'The OS language is:\s*(.+)') {
            $result.OSLanguage = $Matches[1].Trim()
        }

        # === Command String ===
        if ($line -match 'Message:\s*The command is:\s*(.+)') {
            $result.CommandString = $Matches[1].Trim()
        }

        # === Search Scope ===
        if ($line -match 'Message:\s*Searching for Updates:\s*(\w)') {
            $result.SearchScope = $Matches[1].Trim()
        }

        # === Notify Method / Action ===
        if ($line -match 'Message:\s*Notify method:\s*(\w+)') {
            $result.ActionType = $Matches[1].Trim()
        }

        # === MTM ===
        if ($line -match 'Message:\s*MTM is:\s*(.+)') {
            $result.MTM = $Matches[1].Trim()
        }

        # === System Properties Block ===
        if ($line -match 'Message:\s*The System Properties are:') {
            $inSystemProps = $true
            $systemPropsLines = @()
            continue
        }
        if ($inSystemProps) {
            if ($line -match '^\s*$' -and $systemPropsLines.Count -ge 3) {
                $inSystemProps = $false
            }
            elseif ($line -match '^\S' -and $line -notmatch '^\s') {
                # Next log entry level token (Info, Severe, Warning)
                if ($systemPropsLines.Count -ge 3) {
                    $inSystemProps = $false
                }
                elseif ($line -match '^(Info|Severe|Warning)\s') {
                    $inSystemProps = $false
                }
                else {
                    $systemPropsLines += $line.Trim()
                }
            }
            else {
                $trimmed = $line.Trim()
                if ($trimmed -ne '' -and $trimmed -notmatch '^(Info|Severe|Warning)\s') {
                    $systemPropsLines += $trimmed
                }
                elseif ($trimmed -match '^(Info|Severe|Warning)\s') {
                    $inSystemProps = $false
                }
            }

            if ($systemPropsLines.Count -ge 3 -and -not $inSystemProps) {
                if ($result.MTM -eq "(not found)") {
                    $result.MTM = $systemPropsLines[0]
                }
                $result.OS = $systemPropsLines[1]
                if ($result.OSLanguage -eq "(not found)") {
                    $result.OSLanguage = $systemPropsLines[2]
                }
            }
            continue
        }

        # === Candidate List (first occurrence only) ===
        if ($line -match 'Message:\s*Candidate list:' -and -not $candidateListFound) {
            $inCandidateList = $true
            $candidateListFound = $true
            continue
        }
        if ($inCandidateList) {
            $trimmed = $line.Trim()
            if ($trimmed -eq '' -or $trimmed -match '^(Info|Severe|Warning)\t') {
                $inCandidateList = $false
            }
            else {
                # Parse update name and reboot type
                if ($trimmed -match '^(.+?)\[reboot type (\d+)\]$') {
                    $result.CandidateList += [PSCustomObject]@{
                        Name       = $Matches[1].Trim()
                        RebootType = $Matches[2]
                    }
                }
                else {
                    # Line without reboot type info
                    $result.CandidateList += [PSCustomObject]@{
                        Name       = $trimmed
                        RebootType = "-1"
                    }
                }
            }
            if ($inCandidateList) { continue }
        }

        # === UpdateResponse Size ===
        if ($line -match 'Message:\s*The size for the UpdateResponse is (\d+)') {
            $updateResponseSizes += [int]$Matches[1]
        }

        # === Installation Success ===
        if ($line -match 'Message:\s*Update (.+?) was installed successfully') {
            $result.InstalledUpdates += $Matches[1].Trim()
        }

        # === Installation Failure ===
        if ($line -match 'Message:\s*Update (.+?) installation failed') {
            $failedName = $Matches[1].Trim()
            $result.FailedUpdates += $failedName

            # Look backward for the failure reason
            $reason = ""

            # Check for signature failure or return code in the preceding lines
            for ($j = $i - 1; $j -ge [Math]::Max(0, $i - 20); $j--) {
                if ($lines[$j] -match 'Message:\s*Package Signature Verification Failed,\s*ID:(.+)') {
                    $reason = "Package Signature Verification Failed ($($Matches[1].Trim()))"
                    break
                }
                if ($lines[$j] -match 'Message:\s*Expected return code:\s*(.+?),\s*Installation return code:\s*(\d+)') {
                    $expected = $Matches[1].Trim()
                    $actual = $Matches[2].Trim()
                    $reason = "Expected return code: $expected, Installation return code: $actual"
                    break
                }
            }

            if ($reason) {
                $result.FailureReasons[$failedName] = $reason
            }
        }

        # === Packages Processed at Shutdown ===
        if ($line -match '^Severe' -and $i + 2 -lt $lineCount) {
            if ($lines[$i + 2] -match 'Message:\s*Processing the Update:\s*(.+)') {
                $result.ProcessedAtShutdown += $Matches[1].Trim()
            }
        }

        # === Severe Entries ===
        if ($line -match '^Severe\s') {
            # Collect the message from the next lines
            $severeMsg = ""
            for ($k = $i + 1; $k -lt [Math]::Min($lineCount, $i + 4); $k++) {
                if ($lines[$k] -match 'Message:\s*(.+)') {
                    $severeMsg = $Matches[1].Trim()
                    break
                }
            }
            # Exclude routine .NET framework message
            if ($severeMsg -and $severeMsg -notmatch '^Application runs with the framework:') {
                $result.SevereEntries += $severeMsg
            }
        }

        # === Warning Entries ===
        if ($line -match '^Warning\s') {
            $warnMsg = ""
            for ($k = $i + 1; $k -lt [Math]::Min($lineCount, $i + 4); $k++) {
                if ($lines[$k] -match 'Message:\s*(.+)') {
                    $warnMsg = $Matches[1].Trim()
                    break
                }
            }
            if ($warnMsg) {
                $result.WarningEntries += $warnMsg
            }
        }
    }

    # Post-processing

    # Use the first UpdateResponse size if available
    if ($updateResponseSizes.Count -gt 0) {
        $result.ApplicableCount = $updateResponseSizes[0]
    }
    else {
        $result.ApplicableCount = $result.CandidateList.Count
    }

    # Determine scan-only
    if ($result.ActionType -eq "NOTIFY" -or
        ($result.InstalledUpdates.Count -eq 0 -and $result.FailedUpdates.Count -eq 0)) {
        $result.IsScanOnly = $true
    }

    # Reboot summary based on installed updates' reboot types
    $installedRebootTypes = @()
    foreach ($installed in $result.InstalledUpdates) {
        $match = $result.CandidateList | Where-Object { $installed -like "$($_.Name)*" -or $_.Name -like "$installed*" } | Select-Object -First 1
        if ($match) {
            $installedRebootTypes += $match.RebootType
        }
    }

    if ($installedRebootTypes -contains "1") {
        $result.RebootSummary = "Reboot required"
    }
    elseif ($installedRebootTypes -contains "3") {
        $result.RebootSummary = "Reboot recommended"
    }
    else {
        $result.RebootSummary = "No reboot needed"
    }

    return $result
}

function Format-Summary {
    param(
        [object]$Data,
        [switch]$IsVerbose
    )

    $lines = @()
    $divider = "=" * 64

    $lines += $divider
    $lines += " THININSTALLER SESSION SUMMARY"
    $lines += $divider
    $lines += "Log File     : $($Data.FileName)"
    $lines += "Session Date : $($Data.SessionDateStr)"
    $lines += "TI Version   : $($Data.TIVersion)  (Build: $($Data.TIBuildDate))"
    $lines += "Windows      : $($Data.WindowsVersion)"
    $lines += ""
    $lines += "SYSTEM"
    $lines += "  Machine Type : $($Data.MTM)"
    $lines += "  OS           : $($Data.OS)"

    # Language line
    $langParts = @()
    if ($Data.OSLanguage -ne "(not found)") { $langParts += "$($Data.OSLanguage) (OS)" }
    if ($Data.ActiveLanguage -ne "(not found)") { $langParts += "Active: $($Data.ActiveLanguage)" }
    if ($Data.DefaultLanguage -ne "(not found)") { $langParts += "Default: $($Data.DefaultLanguage)" }
    if ($langParts.Count -gt 0) {
        $lines += "  Language     : $($langParts -join '  |  ')"
    }
    else {
        $lines += "  Language     : (not found)"
    }

    $lines += ""
    $lines += "SESSION CONFIGURATION"
    $lines += "  Search Scope : $(Get-SearchScopeLabel $Data.SearchScope)"
    $lines += "  Action       : $($Data.ActionType)"
    $lines += "  Command      : $($Data.CommandString)"

    $lines += ""
    $candidateCount = $Data.CandidateList.Count
    $lines += "APPLICABLE UPDATES  ($($Data.ApplicableCount) found)"

    if ($candidateCount -eq 0) {
        $lines += "  (no applicable updates found)"
    }
    else {
        $showCount = if ($IsVerbose) { $candidateCount } else { [Math]::Min(10, $candidateCount) }
        for ($i = 0; $i -lt $showCount; $i++) {
            $update = $Data.CandidateList[$i]
            $rebootLabel = Get-RebootTypeLabel $update.RebootType
            $lines += "  $($update.Name)  [$rebootLabel]"
        }
        if (-not $IsVerbose -and $candidateCount -gt 10) {
            $remaining = $candidateCount - 10
            $lines += "  ... ($remaining more - use -Verbose for full list)"
        }
    }

    $lines += ""
    $lines += "INSTALLATION RESULTS"

    if ($Data.IsScanOnly -and $Data.ActionType -eq "NOTIFY") {
        $lines += "  (scan only - no installs performed)"
    }
    elseif ($Data.IsScanOnly) {
        $installedCount = $Data.InstalledUpdates.Count
        $failedCount = $Data.FailedUpdates.Count
        $lines += "  Installed    : $installedCount"
        $lines += "  Failed       : $failedCount"
        $lines += "  (no installs were performed)"
    }
    else {
        $installedCount = $Data.InstalledUpdates.Count
        $failedCount = $Data.FailedUpdates.Count
        $lines += "  Installed    : $installedCount"
        $lines += "  Failed       : $failedCount"
        $lines += "  Reboot       : $($Data.RebootSummary)"

        if ($installedCount -gt 0) {
            $lines += ""
            $lines += "  INSTALLED:"
            foreach ($u in $Data.InstalledUpdates) {
                $lines += "    [OK] $u"
            }
        }

        if ($failedCount -gt 0) {
            $lines += ""
            $lines += "  FAILED:"
            foreach ($u in $Data.FailedUpdates) {
                $reason = if ($Data.FailureReasons.ContainsKey($u)) { $Data.FailureReasons[$u] } else { "Unknown" }
                $lines += "    [FAIL] $u"
                $lines += "           Reason: $reason"
            }
        }
    }

    if ($Data.ProcessedAtShutdown.Count -gt 0) {
        $lines += ""
        $lines += "  PROCESSED AT SHUTDOWN:"
        foreach ($p in $Data.ProcessedAtShutdown) {
            $lines += "    $p"
        }
    }

    $lines += ""
    $lines += "ERRORS / WARNINGS"

    $hasErrors = $Data.SevereEntries.Count -gt 0
    $hasWarnings = $Data.WarningEntries.Count -gt 0

    if (-not $hasErrors -and -not $hasWarnings) {
        $lines += "  (none)"
    }
    else {
        if ($hasErrors) {
            $severeToShow = if ($IsVerbose) { $Data.SevereEntries } else { $Data.SevereEntries | Select-Object -Unique }
            foreach ($s in $severeToShow) {
                $lines += "  [SEVERE] $s"
            }
        }
        if ($hasWarnings) {
            foreach ($w in $Data.WarningEntries) {
                $lines += "  [WARNING] $w"
            }
        }
    }

    $lines += $divider

    return $lines
}

function Write-SummaryToConsole {
    param(
        [string[]]$Lines
    )

    foreach ($line in $Lines) {
        if ($line -match '^\={10,}') {
            Write-ColorHost $line -ForegroundColor Cyan
        }
        elseif ($line -match '^\s*THININSTALLER SESSION SUMMARY') {
            Write-ColorHost $line -ForegroundColor Cyan
        }
        elseif ($line -match '^\s*\[OK\]') {
            Write-ColorHost $line -ForegroundColor Green
        }
        elseif ($line -match '^\s*\[FAIL\]') {
            Write-ColorHost $line -ForegroundColor Red
        }
        elseif ($line -match '^\s*Reason:') {
            Write-ColorHost $line -ForegroundColor Red
        }
        elseif ($line -match '^\s*\[SEVERE\]') {
            Write-ColorHost $line -ForegroundColor Red
        }
        elseif ($line -match '^\s*\[WARNING\]') {
            Write-ColorHost $line -ForegroundColor Yellow
        }
        elseif ($line -match '^\s*Failed\s+:\s*[1-9]') {
            Write-ColorHost $line -ForegroundColor Red
        }
        elseif ($line -match '^\s*Installed\s+:\s*[1-9]') {
            Write-ColorHost $line -ForegroundColor Green
        }
        elseif ($line -match 'scan only|no installs|no applicable') {
            Write-ColorHost $line -ForegroundColor Yellow
        }
        elseif ($line -match '^(SYSTEM|SESSION CONFIGURATION|APPLICABLE UPDATES|INSTALLATION RESULTS|ERRORS / WARNINGS)') {
            Write-ColorHost $line -ForegroundColor White
        }
        else {
            Write-ColorHost $line -ForegroundColor Gray
        }
    }
}

#endregion

#region Main Logic

# Validate parameters
if (-not $LogFile -and -not $LogDirectory) {
    Write-Error "You must specify either -LogFile or -LogDirectory."
    return
}

if ($LogFile -and $LogDirectory) {
    Write-Error "Specify only one of -LogFile or -LogDirectory, not both."
    return
}

# Collect files to process
$filesToProcess = @()

if ($LogFile) {
    if (-not (Test-Path -Path $LogFile)) {
        Write-Error "File not found: $LogFile"
        return
    }
    $resolvedPath = (Resolve-Path $LogFile).Path
    if (-not (Test-ThinInstallerLog $resolvedPath)) {
        Write-Error "Not a valid ThinInstaller log file (missing '[Thin Installer build:' header): $LogFile"
        return
    }
    $filesToProcess += $resolvedPath
}

if ($LogDirectory) {
    if (-not (Test-Path -Path $LogDirectory -PathType Container)) {
        Write-Error "Directory not found: $LogDirectory"
        return
    }
    $candidates = Get-ChildItem -Path $LogDirectory -File | Where-Object {
        $_.Extension -in @('.txt', '.log')
    }
    foreach ($candidate in $candidates) {
        if (Test-ThinInstallerLog $candidate.FullName) {
            $filesToProcess += $candidate.FullName
        }
        else {
            Write-Warning "Skipping non-ThinInstaller file: $($candidate.Name)"
        }
    }
    if ($filesToProcess.Count -eq 0) {
        Write-Error "No valid ThinInstaller log files found in: $LogDirectory"
        return
    }
}

# Parse all files and sort by session timestamp
$parsedResults = @()
foreach ($file in $filesToProcess) {
    $parsed = ParseThinInstallerLog -FilePath $file
    if ($parsed) {
        $parsedResults += $parsed
    }
}

# Sort by session date when processing multiple files
if ($parsedResults.Count -gt 1) {
    $parsedResults = $parsedResults | Sort-Object {
        if ($_.SessionDateTime) { $_.SessionDateTime } else { [DateTime]::MinValue }
    }
}

# Generate summaries
$allSummaryLines = @()
$isVerbose = $PSCmdlet.MyInvocation.BoundParameters.ContainsKey('Verbose') -or $VerbosePreference -eq 'Continue'

# Add file header for output file
if ($OutputFile) {
    $allSummaryLines += "$ScriptName v$ScriptVersion - Generated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $allSummaryLines += ""
}

$fileIndex = 0
foreach ($parsed in $parsedResults) {
    $summaryLines = Format-Summary -Data $parsed -IsVerbose:$isVerbose

    # Console output
    Write-SummaryToConsole -Lines $summaryLines

    # Collect for file output
    $allSummaryLines += $summaryLines

    $fileIndex++
    if ($fileIndex -lt $parsedResults.Count) {
        Write-Host ""
        $allSummaryLines += ""
    }
}

# Multi-file count
if ($parsedResults.Count -gt 1) {
    $countMsg = "Processed $($parsedResults.Count) log files"
    Write-Host ""
    Write-ColorHost $countMsg -ForegroundColor Cyan
    $allSummaryLines += ""
    $allSummaryLines += $countMsg
}

# Write to output file if requested
if ($OutputFile) {
    $outputDir = Split-Path -Path $OutputFile -Parent
    if ($outputDir -and -not (Test-Path -Path $outputDir)) {
        try {
            New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        }
        catch {
            Write-Error "Cannot create output directory: $outputDir - $_"
            return
        }
    }

    if ((Test-Path -Path $OutputFile) -and -not $Force) {
        $response = Read-Host "Output file '$OutputFile' already exists. Overwrite? (Y/N)"
        if ($response -notmatch '^[Yy]') {
            Write-Host "Output file not written."
            return
        }
    }

    try {
        $allSummaryLines | Out-File -FilePath $OutputFile -Encoding UTF8 -Force
        Write-ColorHost "Summary written to: $OutputFile" -ForegroundColor Green
    }
    catch {
        Write-Error "Failed to write output file: $_"
        return
    }
}

#endregion

}

# SIG # Begin signature block
