<#
  .SYNOPSIS
  Returns list of applicable updates based on specified Applicability Rules
  Trace log file generated by Lenovo System Update or Thin Installer.

  .DESCRIPTION
  Read an Update_ApplicabilityRulesTrace.txt from Thin Installer or
  ApplicabilityRulesTrace.txt from Lenovo System Update and show list of
  package IDs that are applicable.  This output string can be passed to
  the Get-LnvUpdatesRepo cmdlet in the -PackageList parameter to create
  a local repository of just the specified updates.

  .PARAMETER Path
  Mandatory: True

  .EXAMPLE
  Show-LnvApplicabileUpdates -Path 'c:\Program Files (x86)\Lenovo\Thin Installer\logs\Update_ApplicabilityRulesTrace.txt'
  .INPUTS

  .OUTPUTS

  .NOTES

#>


function Show-LnvApplicableUpdate {
    param (
        [parameter(position = 0, Mandatory = $true, helpMessage = "Enter the path to a valid ApplicabilityRulesTrace.txt file")]
        [String] $Path
    )

    if (Test-Path -Path $Path) {
        $lines = Get-Content -Path $Path

        $n = 0
        $packageids = ""
        foreach ($line in $lines) {
            if ($line -eq "   -Dependencies(True), ") {
                $packageids += $lines[$n-1].Trim('-',' ') + ", "
            }
            $n += 1
        }
        Write-Output $packageids.TrimEnd(', ')
    }
}


# SIG # Begin signature block
