#
# Module manifest for module 'msp360'
#
# Generated by: MSP360 Onboarding Team <services@msp360.com>
#
# Generated on: 7/20/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'msp360.psm1'

# Version number of this module.
ModuleVersion = '3.29.201'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '69079da4-a0de-426d-bece-ae139c8b5f1a'

# Author of this module
Author = 'MSP360 Onboarding Team <services@msp360.com>'

# Company or vendor of this module
CompanyName = 'MSP360'

# Copyright statement for this module
Copyright = '(c) 2023 MSP360. All rights reserved.'

# Description of the functionality provided by this module
Description = 'The module includes cmdlets to manage MSP360 (CloudBerry) Backup agent, MBS API and tools.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'MBS','MSP360','CloudBerry','API','OnlineBackup','Backup','MSP','mspbackups'

        # A URL to the license for this module.
        LicenseUri = 'https://opensource.org/licenses/Apache-2.0'

        # A URL to the main website for this project.
        ProjectUri = 'https://mspbackups.com/AP/Help/powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://www.msp360.com/img/pages/company/downloads/msp360-logo.png?v=2'

        # ReleaseNotes of this module
        ReleaseNotes = '- Bugfix:
    - Edit-MBSNBFBackupPlan: cannot switch to FFI schedule when GFS settings are enabled and vice versa
    - Get-MBSBackupPlan: ''Cannot bind argument to parameter ''ReferenceObject'' because it is null.'' error when parsing full shcedule values in some cases
    - New-MBSNBFFileBackupPlan, New-MBSNBFIBBBackupPlan, Edit-MBSNBFBackupPlan: ''Incorrect value for -gfsYMonth. The value ''...'' must be integer'' error if -GFSMonthOfTheYear parameter is specified
    - New-MBSNBFFileBackupPlan, New-MBSBackupPlan, Edit-MBSNBFBackupPlan, Edit-MBSBackupPlan: incorrect separators used when parsing array values for -SkipFolder, -IncludeFilesMask, -ExcludeFilesMask parameters
    - New-MBSNBFFileBackupPlan: -SkipFolder parameter does not work
    - Edit-MBSBackupPlan: cannot combine backup chain parameters with other parameters in one command
- Enhancement:
    - Install-MBSAgent, Install-RMMAgent, Install-CONAgent: URL request and error handling improvements
    - Get-MBSAPIBuild: added ''RMMLinuxDEB'',''RMMLinuxRPM'',''RMMmacOS'' values and renamed ''RMM'' to ''RMMWindows'' for the -Type parameter'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
