name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        cmd:
          - python android_bulletins_parser.py
          - python get_json.py https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=440 network_config_tf2.json
          - python get_json.py https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize microsoft_instance_discovery.json
          - python get_json.py https://login.microsoftonline.com/common/.well-known/openid-configuration microsoft_oidc_config.json
          - python get_json.py https://login.windows-ppe.net/common/.well-known/openid-configuration microsoft_oidc_config_ppe.json
          - python get_json.py https://login.microsoftonline.com/common/discovery/keys microsoft_jwks.json
          - python get_json.py https://login.microsoftonline.us/common/discovery/keys microsoft_jwks_us.json
          - python get_json.py https://login.partner.microsoftonline.cn/common/discovery/keys microsoft_jwks_cn.json
          - python get_json.py https://login.windows-ppe.net/common/discovery/keys microsoft_jwks_ppe.json
          # TODO decode https://login.microsoftonline.com/common/kerberos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -r requirements.txt
      - run: ${{ matrix.cmd }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "data: ${{ matrix.cmd }}"
