name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        cmd:
          - python android_bulletins_parser.py
          - python get_json.py
          # 30s+ request
          - python get_json.py https://3rdpartysource.microsoft.com/downloads microsoft_3rdpartysource.json
          # TODO decode https://login.microsoftonline.com/common/kerberos
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -r requirements.txt
      - run: ${{ matrix.cmd }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "data: ${{ matrix.cmd }}"
