name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      models: read
    environment: dev
    strategy:
      matrix:
        cmd:
          - android_bulletins_parser.py
          - get.py
          - microsoft_download_center.py
          - powershell_gallery.py
          - microsoft_3rdpartysource.py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x
          cache: pip
      # azure-identity doesn't support GitHub WIF
      - uses: azure/login@v2.2.0
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
      - run: pip install -r requirements.txt

      - run: python -u ${{ matrix.cmd }}
        env:
          AZURE_STORAGE_IN: ${{ secrets.AZURE_STORAGE_IN }}
          AZURE_STORAGE_OUT: ${{ secrets.AZURE_STORAGE_OUT }}

      - name: Generate prompt
        id: prompt
        shell: /usr/bin/bash {0}
        run: |
          cat << EOF > ../prompt
          Generate a commit message summarising the changes in the following git diff.
          The message should contain a one-line summary of the changes, and a newline-separated list of the changes.
          The one-line summary should be specific. Do not use generic phrases like "Updated configuration files with multiple improvements and enhancements" 
          Respond with only the commit message and no other text. Do not use markdown formatting.

          Here is the diff:
          EOF

          git add .
          git diff --cached --exit-code >> ../prompt
          echo "changed=$?" >> $GITHUB_OUTPUT
      - id: inference
        if: steps.prompt.outputs.changed == '1'
        continue-on-error: true
        uses: actions/ai-inference@main
        with:
          prompt-file: ../prompt
          model: ${{ vars.MODEL }}
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: prompt-file
          path: ../prompt
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "data(${{ matrix.cmd }}): ${{ steps.inference.outputs.response || 'change detected' }}"
          pull: "--rebase --autostash"
