name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: dev
    strategy:
      matrix:
        cmd:
          - python -u android_bulletins_parser.py
          - python -u get.py
          - python -u microsoft_download_center.py --start 108100 --end 108200 --threads 16 --delay 0.01
          - python -u powershell_gallery.py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x
          cache: pip
      # azure-identity doesn't support GitHub WIF
      - uses: azure/login@v2.2.0
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
      - run: pip install -r requirements.txt
      - run: ${{ matrix.cmd }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "data: ${{ matrix.cmd }}"
          pull: "--rebase --autostash"
