# some scripts are expensive
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        cmd:
          - python -u microsoft_3rdpartysource.py
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.x
          cache: pip
      - run: pip install -r requirements.txt
      - run: ${{ matrix.cmd }}
        env:
          AZURE_STORAGE_IN: ${{ secrets.AZURE_STORAGE_IN }}
          AZURE_STORAGE_OUT: ${{ secrets.AZURE_STORAGE_OUT }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "data: ${{ matrix.cmd }}"
          pull: "--rebase --autostash"
